DROP TABLE CLUB
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CLUB;

CREATE TABLE CLUB (
    CLUBSEQ NUMBER CONSTRAINT PK_CLUB_01 PRIMARY KEY,
    CLUBTITLE VARCHAR2(200),
    CLUBTEXT VARCHAR2(4000),
    CLUBDATE DATE,
    MEMBERNUM NUMBER,
    CONSTRAINT FK_CLUB_01 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM),
    CLUBIMAGE VARCHAR2(50)
);

CREATE SEQUENCE SEQ_CLUB
START WITH 1000
INCREMENT BY 1;

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, 'A모임', '놀러오세요', SYSDATE, 100, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, 'B모임', '놀자', SYSDATE, 101, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, 'C모임', '즐거운', SYSDATE, 102, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, 'D모임', '강아지 관련', SYSDATE, 103, '24353');

INSERT INTO CLUB(CLUBSEQ, CLUBTITLE, CLUBTEXT, CLUBDATE, MEMBERNUM, CLUBIMAGE)
VALUES (SEQ_CLUB.NEXTVAL, 'E모임', '고양이 관련', SYSDATE, 104, '24353');


SELECT * FROM CLUB;

-- 클럽장
SELECT C.CLUBSEQ, C.CLUBTITLE, M.MEMBERNUM, M.USERID
FROM CLUB C, MEMBERS M
WHERE C.MEMBERNUM = M.MEMBERNUM;

-- 클럽에 가입한 멤버들
SELECT C.CLUBSEQ, C.CLUBTITLE, M.MEMBERNUM, M.USERID
FROM CLUB C, MEMBERS M, CLUBLINK CL
WHERE C.CLUBSEQ = CL.CLUBSEQ
		AND M.MEMBERNUM = CL.MEMBERNUM;

SELECT 
FROM CLUB C, 
		
SELECT MA.MEMBERNUM, CL.CLUBSEQ, CA.BOOKNUM, CA.CARDSEQ
FROM CLUB CL, CARD CA, MEMBERS MA
WHERE CL.CLUBSEQ = CA.CLUBSEQ
		AND CL.MEMBERNUM = MA.MEMBERNUM;
		
SELECT RNUM, CL.CLUBSEQ, CL.CLUBTITLE, CL.CLUBIMAGE, CL.CLUBDATE
   FROM ( SELECT ROW_NUMBER()OVER( COUNT(CA.CARDSEQ)OVER(PARTITION BY CA.CLUBSEQ ORDER BY CA.CARDSEQ DESC TA.TALKSEQ DESC) ) AS RNUM, CL.CLUBSEQ, CL.CLUBTITLE, CL.CLUBIMAGE, CL.CLUBDATE 
      	FROM CARD CA, TALK TA, CLUB CL
     	 WHERE CA.CARDSEQ = TA.CARDSEQ
            AND CL.CLUBSEQ = CA.CLUBSEQ );

RNUM 
FROM (SELECT ROW_NUMBER() OVER (PARTITION BY CATEGORIES ORDER BY GRADE DESC) AS RNUM, BOOKNUM, BOOKTITLE, CATEGORIES, BOOKREADCOUNT, BOOKDEL, GRADE, "
							+ " AUTHOR, ISSUEDATE, BOOKHEADER, PUBLISHER " 
					+ " FROM BOOK) "
				+ "	WHERE RNUM = 1 "            


SELECT RNUM, CL.CLUBSEQ, CL.CLUBTITLE, CL.CLUBIMAGE, CL.CLUBDATE
FROM (SELECT ROW_NUMBER()OVER(PARTITION BY CL.CLUBSEQ ORDER BY CA.CARDSEQ DESC) AS RNUM, CL.CLUBSEQ, CL.CLUBTITLE, CL.CLUBIMAGE, CL.CLUBDATE 
		FROM CARD CA, CLUB CL, TALK TA
     	 WHERE CL.CLUBSEQ = CA.CLUBSEQ 
     	 ) 
