DROP TABLE CLUBLINK
CASCADE CONSTRAINTS;

CREATE TABLE CLUBLINK (
    CLUBSEQ NUMBER,
    CONSTRAINT FK_CLUBLINK_01 FOREIGN KEY(CLUBSEQ) 
    REFERENCES CLUB(CLUBSEQ),
    MEMBERNUM NUMBER,
    CONSTRAINT FK_CLUBLINK_02 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM)
);