DROP TABLE CLUBLINK
CASCADE CONSTRAINTS;

CREATE TABLE CLUBLINK (
    CLUBSEQ NUMBER,
    CONSTRAINT FK_CLUBLINK_01 FOREIGN KEY(CLUBSEQ) 
    REFERENCES CLUB(CLUBSEQ),
    MEMBERNUM NUMBER,
    CONSTRAINT FK_CLUBLINK_02 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM)
);

INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1000, 103);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1000, 104);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1001, 105);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1001, 103);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1001, 104);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1002, 101);
 
 INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1002, 103);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1002, 100);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1003, 100);
 
 INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1003, 101);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1003, 102);
 
 INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1003, 103);
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1003, 104);
 
 INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1004, 102);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1004, 103);
 
  INSERT INTO CLUBLINK(CLUBSEQ, MEMBERNUM)
 VALUES (1004, 101);

 SELECT * FROM CLUBLINK;