DROP TABLE MEMBERS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MEMBERS;

CREATE TABLE MEMBERS (
    MEMBERNUM NUMBER CONSTRAINT PK_MEMBERS_01 PRIMARY KEY,
    USERID VARCHAR2(20),
    PWD VARCHAR2(20),
    EMAIL VARCHAR2(50),
    GENDER NUMBER,
    PHONE VARCHAR2(50),
    BIRTH DATE,
    ACTIVITY NUMBER,
    WEBMANAGER NUMBER,
    CLUBMASTER NUMBER
);

CREATE SEQUENCE SEQ_MEMBERS
START WITH 100
INCREMENT BY 1;