DROP TABLE MEMBERS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MEMBERS;

CREATE TABLE MEMBERS (
    MEMBERNUM NUMBER CONSTRAINT PK_MEMBERS_01 PRIMARY KEY,
    USERID VARCHAR2(20),
    PWD VARCHAR2(20),
    EMAIL VARCHAR2(50),
    GENDER NUMBER,
    PHONE VARCHAR2(50),
    BIRTH DATE,
    ACTIVITY NUMBER,
    WEBMANAGER NUMBER,
    CLUBMASTER NUMBER 	--클럽 마스터인지 유뮤
);

--0:man 1:woman
--0:user 3:webmanager

CREATE SEQUENCE SEQ_MEMBERS
START WITH 100
INCREMENT BY 1;

SELECT * FROM MEMBERS


SELECT MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, WEBMANAGER, CLUBMASTER, RNUM
FROM (SELECT ROW_NUMBER()OVER(ORDER BY ACTIVITY DESC) AS RNUM, MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, WEBMANAGER, CLUBMASTER
	  FROM MEMBERS)
WHERE RNUM BETWEEN 1 AND 5;

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, WEBMANAGER, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'A', 'aaa', 'A@naver.com', 0, '0100000124', '2001/10/27', 24, 0, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, WEBMANAGER, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'SC', 'glkfd', 'SV@naver.com', 1, '010004855', '1992/10/17', 23, 0, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, WEBMANAGER, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'WEV', 'efw', 'WEG@naver.com', 1, '01000514', '1995/02/25', 44, 0, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, WEBMANAGER, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'EWT', 'aaa', 'ERHA@naver.com', 0, '010545646', '1994/05/10', 62, 0, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, WEBMANAGER, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'ERE', 'aaa', 'EWF@naver.com', 0, '0100046456', '1980/08/22', 133, 0, 0);

INSERT INTO MEMBERS (MEMBERNUM, USERID, PWD, EMAIL, GENDER, PHONE, BIRTH, ACTIVITY, WEBMANAGER, CLUBMASTER)
VALUES(SEQ_MEMBERS.NEXTVAL, 'WQRWQ', 'aaa', 'WER@naver.com', 1, '0104846522', '1999/10/07', 58, 0, 0);


