DROP TABLE MYLIBRARY
CASCADE CONSTRAINTS;

CREATE TABLE MYLIBRARY (
    MEMBERNUM NUMBER,
    CONSTRAINT FK_MYOFFICE_01 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM),
    WISHBOOK NUMBER,
    CONSTRAINT FK_MYOFFICE_02 FOREIGN KEY(WISHBOOK) 
    REFERENCES BOOK(BOOKNUM),
    READBOOK NUMBER,
    CONSTRAINT FK_MYOFFICE_03 FOREIGN KEY(READBOOK) 
    REFERENCES BOOK(BOOKNUM)
);

