DROP TABLE REVIEW
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW (
    REVSEQ NUMBER CONSTRAINT PK_REVIEW_01 PRIMARY KEY,
    REVCONTENT VARCHAR2(4000),
    REVDATE DATE,
    REVREADCOUNT NUMBER,
    BOOKNUM NUMBER,
    CONSTRAINT FK_REVIEW_01 FOREIGN KEY(BOOKNUM) 
    REFERENCES BOOK(BOOKNUM),
    MEMBERNUM NUMBER,
    CONSTRAINT FK_REVIEW_02 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM),
    RATING NUMBER,
    REVREF NUMBER,
    REVSTEP NUMBER,
    REVDEPTH NUMBER
);

CREATE SEQUENCE SEQ_REVIEW
START WITH 1
INCREMENT BY 1;