DROP TABLE SCHEDULE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MEMBER;

CREATE TABLE SCHEDULE (
    SCHEDULESEQ NUMBER CONSTRAINT PK_SCHEDULE_01 PRIMARY KEY,
    BOOKNUM NUMBER,
    CONSTRAINT FK_SCHEDULE_01 FOREIGN KEY(BOOKNUM) 
    REFERENCES BOOK(BOOKNUM), 
    MEMBERNUM NUMBER,
    CONSTRAINT FK_SCHEDULE_02 FOREIGN KEY(MEMBERNUM) 
    REFERENCES MEMBERS(MEMBERNUM),
    SUBSCRIBE NUMBER,
    SCHSTART DATE,
    SCHEND DATE
);

CREATE SEQUENCE SEQ_MEMBER
START WITH 1
INCREMENT BY 1;